#!/bin/sh

set -e

fail() {
     echo $1 >&2
     exit 1
}

curdir=$(cd $(dirname $0); pwd)
topdir=$(dirname $curdir)

psycopg=$(grep -E '^psycopg.* +--no-binary +psycopg2' \
$topdir/requirements.txt) || fail "psycopg2 is not using --no-binary anymore"

$topdir/.btw-venv/bin/pip freeze | sed -e'/^psycopg2.*/ s/$/ --no-binary psycopg2/' | grep -v pkg-resources== > frozen-requirements.txt
