# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 11:56


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semantic_fields', '0003_auto_20160407_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecifiedSemanticField',
            fields=[
                ('semanticfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='semantic_fields.SemanticField')),
            ],
            options={
                'managed': False,
            },
            bases=('semantic_fields.semanticfield',),
        ),
        migrations.AlterField(
            model_name='lexeme',
            name='semantic_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lexemes', to='semantic_fields.SemanticField'),
        ),
    ]
