# Generated by Django 2.2.4 on 2019-08-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexicography', '0007_changerecord_hidden'),
        ('semantic_fields', '0004_auto_20161102_0756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecifiedSemanticField',
        ),
    ]
