version: "3.6"
services:
  # This is a setup for running BTW deployed on an actual server.
  btw:
    environment:
      BTW_ENV: linode
    volumes:
      - type: volume
        source: btw-postgres
        target: /var/lib/postgresql/9.6/main
      - type: volume
        source: btw-exist-db
        target: /var/eXist-db/btw
      - type: volume
        source: btw-system-logs
        target: /var/log/
        # We don't need to worry about uid/gid for the following volumes
        # because they are already set correctly, and the mount does not change
        # them.
      - type: volume
        source: btw-logs
        target: /srv/www/btw/btw/var/log
      - type: volume
        source: btw-redis
        target: /srv/www/btw/btw/var/lib/redis/
      - type: bind
        source: /home/btw/.config/btw/linode
        target: /home/btw/.config/btw/linode
      - type: bind
        source: /root/.btw-backup
        target: /root/.btw-backup
      - type: bind
        source: /root/copy
        target: /root/copy
