version: "3.6"
services:
  # It does not map volumes for btw-backup, as we don't run it in development.
  btw:
    environment:
      BTW_ENV: docker_run_dev
    volumes:
      - type: volume
        source: btw-dev-postgres
        target: /var/lib/postgresql
      - type: volume
        source: btw-dev-exist-db
        target: /var/eXist-db/btw
      - type: volume
        source: btw-dev-system-logs
        target: /var/log/
        # We don't need to worry about uid/gid for the following volumes
        # because they are already set correctly, and the mount does not change
        # them.
      - type: volume
        source: btw-dev-logs
        target: /srv/www/btw/btw/var/log
      - type: volume
        source: btw-dev-redis
        target: /srv/www/btw/btw/var/lib/redis/
      - type: bind
        source: /home/ldd/.config/btw/secrets/docker_run_dev
        target: /home/btw/.config/btw/secrets/docker_run_dev
      - type: bind
        source: /home/ldd/.config/btw/settings/docker_run_dev
        target: /home/btw/.config/btw/settings/docker_run_dev

volumes:
  btw-dev-postgres:
  btw-dev-exist-db:
  btw-dev-system-logs:
  btw-dev-logs:
  btw-dev-redis:
