# This is an override for the base + dev combination. It is meant to be used to
# run the UNCOMMITTED CODE under development.
version: "3.6"
services:
  # It does not map volumes for btw-backup, as we don't run it in development.
  btw:
    volumes:
      # Bind the uncommitted code to where we copy the code.
      - type: bind
        source: ../
        target: /srv/www/btw/btw
