#!/bin/bash

dead () {
    exit 1
}

cleanup () {
    local jobs
    nginx -c `pwd`/build/config/nginx.conf -s stop
    jobs=`jobs -pr`
    if [ -n "$jobs" ]; then
        kill `jobs -pr`
    fi
    exit
}

trap dead SIGCHLD
trap cleanup EXIT
trap cleanup ERR

mkdir -p var/run || true
mkdir -p var/log || true
mkdir -p var/lib/nginx || true
mkdir -p var/log/btw || true

BTW_ENV=selenium ./manage.py test utils/liveserver_test.py --liveserver=localhost:7777 & nginx -c `pwd`/build/config/nginx.conf

wait
