#!/bin/bash

fifo_to_server=$1
shift

fifo_from_server=$1
shift

dead () {
    exit 1
}

cleanup () {
    local jobs
    nginx -c `pwd`/build/config/nginx.conf -s stop
    jobs=`jobs -pr`
    if [ -n "$jobs" ]; then
        kill -9 `jobs -pr`
    fi
    exit
}

trap dead SIGCHLD
trap cleanup EXIT
trap cleanup ERR

mkdir -p var/run || true
mkdir -p var/log || true
mkdir -p var/lib/nginx || true
mkdir -p var/log/btw || true

BTW_ENV=selenium ./manage.py liveserver --settings=btw.test_settings localhost:7777 $fifo_to_server $fifo_from_server & nginx -c `pwd`/build/config/nginx.conf

wait
